#include "init.h"

void RCC_init (void) {
    SET_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIOBEN)
}

void onboard_leds_init (void) {

// green PB0 ручками
*(uint32_t*)(0x40020400UL + 0x00UL) |= 0x01UL; // Moder 0_1
*(uint32_t*)(0x40020400UL + 0x00UL) &= ~0x02UL; // Moder 1_0

*(uint32_t*)(0x40020400UL + 0x04UL) |= 0x00UL; // OTYPER 0_0

*(uint32_t*)(0x40020400UL + 0x08UL) |= 0x01UL; // SPEED 0_1
*(uint32_t*)(0x40020400UL + 0x08UL) &= ~0x02UL; // SPEED 1_0

*(uint32_t*)(0x40020400UL + 0x0CUL) &= ~0x00UL; // PUPDR 0_0 
*(uint32_t*)(0x40020400UL + 0x0CUL) &= ~0x01UL; // PUPDR 1_0

*(uint32_t*)(0x40020400UL + 0x18) |= 0x10000UL; // BSRR reser PB0 output

// blue led PB7 через CMSIS
SET_BIT(GPIOB -> MODER, GPIO_MODER_MODE7_0); // Moder 14_1
CLEAR_BIT(GPIOB -> MODER, GPIO_MODER_MODE7_1); // Moder 15_0

CLEAR_BIT(GPIOB -> OTYPER, GPIO_OTYPER_OT7); // OTYPER 7_0

SET_BIT(GPIOB -> OSPEEDR, GPIO_OSPEEDER_OSPEEDR7_0); // SPEED 14_1
CLEAR_BIT(GPIOB -> OSPEEDR, GPIO_OSPEEDER_OSPEEDR7_1); // SPEED 15_0

CLEAR_BIT(GPIOB -> PUPDR, GPIO_PUPDR_PUPD7_0); // PUPDR 14_0
CLEAR_BIT(GPIOB -> PUPDR, GPIO_PUPDR_PUPD7_1); // PUPDR 15_0

SET_BIT(GPIOB -> BSRR, GPIO_BSRR_BR_7); // // BSRR reset PB7 output


// red led PB14 через собственные директивы
BIT_SET(GPIOB_MODER, GPIOB_PIN_14_GPOut); // MODER14 General-purpose Output
BIT_SET(GPIOB_OTYPER, GPIOB_PIN_14_PushPull); // OTYPER14 push-pull
BIT_SET(GPIOB_OSPEEDR, GPIOB_PIN_14_MEDspd); // OSPEEDR14 Medium
BIT_RESET(GPIOB_PUPDR, GPIOB_PIN_14_NoPullUpPullDown); // PUPDR14 No Pull-Up Pull-Down
BIT_RESET(GPIOB_BSRR, GPIOB_PIN_14_ResetOut); // BSRR14 Reset to 0

}

// Button 1 PB12
void button1_input (void) {
    CLEAR_BIT(GPIOB -> MODER, GPIO_MODER_MODE12_0); //MODER12 00 (input)
    CLEAR_BIT(GPIOB -> MODER, GPIO_MODER_MODE12_1); //MODER12 00 (input)

    SET_BIT(GPIOB -> OTYPER, GPIO_OTYPER_OT12); //OTYPER12 open-drain

    SET_BIT(GPIOB -> OSPEEDR, GPIO_OSPEEDER_OSPEEDR12_0); // OSPEEDR12 10 (Medium speed)
    CLEAR_BIT(GPIOB -> OSPEEDR, GPIO_OSPEEDER_OSPEEDR12_1); // OSPEEDR12 10 (Medium speed)

    CLEAR_BIT(GPIOB -> PUPDR, GPIO_PUPDR_PUPD12_0); // PUPDR12 pull-up
    SET_BIT(GPIOB -> PUPDR, GPIO_PUPDR_PUPD12_1); // PUPDR12 pull-up
}

// Button 2 PB15
void button2_input (void) {
    CLEAR_BIT(GPIOB -> MODER, GPIO_MODER_MODE15_0); //MODER15 00 (input)
    CLEAR_BIT(GPIOB -> MODER, GPIO_MODER_MODE15_1); //MODER15 00 (input)

    SET_BIT(GPIOB -> OTYPER, GPIO_OTYPER_OT15); //OTYPER15 open-drain

    SET_BIT(GPIOB -> OSPEEDR, GPIO_OSPEEDER_OSPEEDR15_0); // OSPEEDR15 10 (Medium speed)
    CLEAR_BIT(GPIOB -> OSPEEDR, GPIO_OSPEEDER_OSPEEDR15_1); // OSPEEDR15 10 (Medium speed)

    CLEAR_BIT(GPIOB -> PUPDR, GPIO_PUPDR_PUPD15_0); // PUPDR15 pull-up
    SET_BIT(GPIOB -> PUPDR, GPIO_PUPDR_PUPD15_1); // PUPDR15 pull-up
}

// Button 3 PB9
void button3_input (void) {
    CLEAR_BIT(GPIOB -> MODER, GPIO_MODER_MODE9_0); //MODER9 00 (input)
    CLEAR_BIT(GPIOB -> MODER, GPIO_MODER_MODE9_1); //MODER9 00 (input)

    SET_BIT(GPIOB -> OTYPER, GPIO_OTYPER_OT9); //OTYPER9 open-drain

    SET_BIT(GPIOB -> OSPEEDR, GPIO_OSPEEDER_OSPEEDR9_0); // OSPEEDR9 10 (Medium speed)
    CLEAR_BIT(GPIOB -> OSPEEDR, GPIO_OSPEEDER_OSPEEDR9_1); // OSPEEDR9 10 (Medium speed)

    CLEAR_BIT(GPIOB -> PUPDR, GPIO_PUPDR_PUPD9_0); // PUPDR9 pull-up
    SET_BIT(GPIOB -> PUPDR, GPIO_PUPDR_PUPD9_1); // PUPDR9 pull-up
}

// led 4 PB7
void led4_output (void) {
    CLEAR_BIT(GPIOB -> MODER, GPIO_MODER_MODE12_0); //MODER12 01 (General-purpose out)
    SET_BIT(GPIOB -> MODER, GPIO_MODER_MODE12_1); //MODER12 01 (General-purpose out)

    CLEAR_BIT(GPIOB -> OTYPER, GPIO_OTYPER_OT12); //OTYPER12 push-pull

    SET_BIT(GPIOB -> OSPEEDR, GPIO_OSPEEDER_OSPEEDR12_0); // OSPEEDR12 10 (Medium speed)
    CLEAR_BIT(GPIOB -> OSPEEDR, GPIO_OSPEEDER_OSPEEDR12_1); // OSPEEDR12 10 (Medium speed)

    CLEAR_BIT(GPIOB -> PUPDR, GPIO_PUPDR_PUPD12_0); // PUPDR12 00 no pull-up pull-down
    CLEAR_BIT(GPIOB -> PUPDR, GPIO_PUPDR_PUPD12_1); // PUPDR12 00 no pull-up pull-down
}

